### ISSUE TITLE
Running localy

### ISSUE THREAD

**Issue by delighttechnology** [mourarezendecas/olx-scraper#3]
Hi,
I am trying to run olx-scraper locally but I can't access page on http://localhost:8080 Could you please give some more explanation how to get it working?
![image](https://github.com/mourarezendecas/olx-scraper/assets/112956117/18f024f1-eb68-4947-b37b-0b19e2c663c1)

**Comment by mourarezendecas** [comment]
Hello friend, first of all, I apologize for the delay in response.

You were not successful in accessing the page on localhost because the service only responds at the /item endpoint when a POST request with the expected JSON is made. The olx-scraper project functions as an API that returns specific JSON responses based on different requests, rather than a conventional web server.

<img width="865" alt="Captura de Tela 2023-08-04 às 00 44 35" src="https://github.com/mourarezendecas/olx-scraper/assets/46174954/b9f6cd94-9581-4292-b4b1-dab990db1802">


I have made a correction in the README.md to make the system's behavior more explicit.

If you have any further questions, feel free to ask. You can also reach out to me on LinkedIn if you prefer.

**Comment by mourarezendecas** [comment]
Hello friend, first of all, I apologize for the delay in response.

You were not successful in accessing the page on localhost because the service only responds at the /item endpoint when a POST request with the expected JSON is made. The olx-scraper project functions as an API that returns specific JSON responses based on different requests, rather than a conventional web server.

<img width="865" alt="Captura de Tela 2023-08-04 às 00 44 35" src="https://github.com/mourarezendecas/olx-scraper/assets/46174954/606843e6-bf06-4ff6-9817-6bcf9bea9c98">


I have made a correction in the README.md to make the system's behavior more explicit.

If you have any further questions, feel free to ask. You can also reach out to me on LinkedIn if you prefer.
